<a href="https://colab.research.google.com/github/ss3299952-cmd/cricket-probablity/blob/main/day2_pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import zipfile
with zipfile.ZipFile("/content/ipl_csv.zip") as z:
  z.extractall("/content/ipl_data")

In [20]:
import os
files = os.listdir("/content/ipl_data")
print(len(files))
print(files[:5])

1245
['392235.json', '1136574.json', '1216508.json', '1426267.json', '1529286.json']

In [19]:
import json
import pandas as pd
with open("/content/ipl_data/1136574.json") as f:
  match =json.load(f)

print(match.keys())
print(match["info"]["teams"])
print(match["info"].get("venue"))
print(match["info"].get("toss"))
print(match["info"].get("outcome"))

dict_keys(['meta', 'info', 'innings'])
['Mumbai Indians', 'Royal Challengers Bangalore']
Wankhede Stadium
{'decision': 'field', 'winner': 'Royal Challengers Bangalore'}
{'winner': 'Mumbai Indians', 'by': {'runs': 46}}

In [22]:
rows = []
for inn_no, inn in enumerate(match["innings"], start = 1):
  for over in inn["overs"]:
    for ball in over ["deliveries"]:
      rows.append({
          "innings" : inn_no,
          "team" : inn["team"],
          "over" : over["over"],
          "batter" : ball["batter"],
          "bowler" : ball["bowler"],
          "runs_batter" : ball["runs"]["batter"],
          "runs_extra" : ball["runs"]["extras"],
          "runs_total" : ball["runs"]["total"],
          "wickets" : 1 if "wickets" in ball else 0,
      })
      df = pd.DataFrame(rows)
      df.head()

In [23]:
df.shape

(251, 9)

In [ ]:
df.info()

In [24]:
df["team"].unique()

array(['Mumbai Indians', 'Royal Challengers Bangalore'], dtype=object)

In [25]:
df["batter"].nunique()
df[["batter" , "runs_batter"]]

           batter  runs_batter
0        SA Yadav            0
1    Ishan Kishan            0
2       RG Sharma            0
3         E Lewis            1
4       RG Sharma            1
..            ...          ...
246       V Kohli            4
247       V Kohli            0
248       V Kohli            6
249       V Kohli            0
250       V Kohli            0

[251 rows x 2 columns]

In [26]:
inn1 = df[df["innings"] == 1]
inn1.shape

(127, 9)

In [49]:
w = df[df["wickets"] == 1]
w[["innings" , "over","batter" , "bowler"]]

     innings  over             batter          bowler
0          1     0           SA Yadav        UT Yadav
1          1     0       Ishan Kishan        UT Yadav
69         1    11            E Lewis     CJ Anderson
95         1    15          RG Sharma     CJ Anderson
113        1    18         KA Pollard       CR Woakes
124        1    19          RG Sharma     CJ Anderson
152        2     4          Q de Kock  MJ McClenaghan
155        2     4     AB de Villiers  MJ McClenaghan
186        2     9      Mandeep Singh       KH Pandya
187        2     9        CJ Anderson       KH Pandya
198        2    11  Washington Sundar       KH Pandya
212        2    13            SN Khan      M Markande
234        2    17          CR Woakes       JJ Bumrah
237        2    17           UT Yadav       JJ Bumrah

In [28]:
df[(df["innings"] == 2) & (df["runs_batter"] >= 4)]

,innings,team,over,batter,bowler,runs_batter,runs_extra,runs_total,wickets
133,2,Royal Challengers Bangalore,0,V Kohli,JJ Bumrah,4,0,4,0
134,2,Royal Challengers Bangalore,1,Q de Kock,KH Pandya,4,0,4,0
136,2,Royal Challengers Bangalore,1,V Kohli,KH Pandya,4,0,4,0
138,2,Royal Challengers Bangalore,1,V Kohli,KH Pandya,4,0,4,0
145,2,Royal Challengers Bangalore,2,V Kohli,MJ McClenaghan,4,0,4,0
146,2,Royal Challengers Bangalore,3,Q de Kock,Mustafizur Rahman,4,0,4,0
150,2,Royal Challengers Bangalore,3,Q de Kock,Mustafizur Rahman,6,0,6,0
158,2,Royal Challengers Bangalore,5,V Kohli,Mustafizur Rahman,4,0,4,0
160,2,Royal Challengers Bangalore,5,Mandeep Singh,Mustafizur Rahman,4,0,4,0
192,2,Royal Challengers Bangalore,10,Washington Sundar,M Markande,4,0,4,0
207,2,Royal Challengers Bangalore,12,SN Khan,JJ Bumrah,4,0,4,0
208,2,Royal Challengers Bangalore,13,V Kohli,M Markande,6,0,6,0
222,2,Royal Challengers Bangalore,15,V Kohli,Mustafizur Rahman,4,0,4,0
224,2,Royal Challengers Bangalore,15,CR Woakes,Mustafizur Rahman,6,0,6,0
226,2,Royal Challengers Bangalore,16,V Kohli,MJ McClenaghan,6,0,6,0
238,2,Royal Challengers Bangalore,18,V Kohli,Mustafizur Rahman,6,0,6,0
242,2,Royal Challengers Bangalore,18,Mohammed Siraj,Mustafizur Rahman,6,0,6,0
246,2,Royal Challengers Bangalore,19,V Kohli,JJ Bumrah,4,0,4,0
248,2,Royal Challengers Bangalore,19,V Kohli,JJ Bumrah,6,0,6,0

In [31]:
df.groupby("team")["runs_total"].sum()

team
Mumbai Indians                 213
Royal Challengers Bangalore    167
Name: runs_total, dtype: int64

In [32]:
top_bat = df.groupby("batter")["runs_batter"].sum()
top_bat = top_bat.sort_values(ascending=False)
top_bat.head(5)

batter
RG Sharma    94
V Kohli      92
E Lewis      65
Q de Kock    19
HH Pandya    17
Name: runs_batter, dtype: int64

In [33]:
bw = df.groupby("bowler")["wickets"].sum()
bw.sort_values(ascending=False).head(5)

bowler
CJ Anderson       3
KH Pandya         3
MJ McClenaghan    2
JJ Bumrah         2
UT Yadav          2
Name: wickets, dtype: int64

In [36]:
df.groupby(["innings", "over"]) ["runs_total"].sum()

innings  over
1        0        3
         1       12
         2        6
         3       19
         4       16
         5        4
         6        3
         7       13
         8        9
         9       10
         10      13
         11       6
         12       4
         13      10
         14      15
         15      10
         16      13
         17      11
         18      15
         19      21
2        0        7
         1       13
         2        7
         3       13
         4        4
         5       11
         6        4
         7        6
         8        5
         9        6
         10       8
         11       3
         12       7
         13      10
         14       4
         15      13
         16      13
         17       3
         18      18
         19      12
Name: runs_total, dtype: int64

In [48]:
runs = df.groupby("batter")["runs_batter"].sum().reset_index()
runs

               batter  runs_batter
0      AB de Villiers            1
1         CJ Anderson            0
2           CR Woakes           11
3             E Lewis           65
4           HH Pandya           17
5        Ishan Kishan            0
6          KA Pollard            5
7           KH Pandya           15
8      MJ McClenaghan            0
9       Mandeep Singh           16
10     Mohammed Siraj            8
11          Q de Kock           19
12          RG Sharma           94
13           SA Yadav            0
14            SN Khan            5
15           UT Yadav            1
16            V Kohli           92
17  Washington Sundar            7

In [46]:
deliveries = df.groupby("batter").size().reset_index(name="deliveries")
deliveries

               batter  deliveries
0      AB de Villiers           2
1         CJ Anderson           1
2           CR Woakes          11
3             E Lewis          44
4           HH Pandya           5
5        Ishan Kishan           1
6          KA Pollard           8
7           KH Pandya          13
8      MJ McClenaghan           1
9       Mandeep Singh          16
10     Mohammed Siraj           3
11          Q de Kock          13
12          RG Sharma          54
13           SA Yadav           1
14            SN Khan           6
15           UT Yadav           2
16            V Kohli          62
17  Washington Sundar           8

In [41]:
bat = runs.merge(deliveries, on="batter")
bat["runs_per_delivery"] = bat["runs_batter"] / bat["deliveries"]
bat.sort_values("runs_per_delivery", ascending=False).head(5)

            batter  runs_batter  deliveries  runs_per_delivery
4        HH Pandya           17           5           3.400000
10  Mohammed Siraj            8           3           2.666667
12       RG Sharma           94          54           1.740741
16         V Kohli           92          62           1.483871
3          E Lewis           65          44           1.477273