<a href="https://colab.research.google.com/github/ss3299952-cmd/cricket-probablity/blob/main/day3_all_matches_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import zipfile
with zipfile.ZipFile("/content/ipl_csv.zip") as z:
  z.extractall("/content/ipl_data")

In [ ]:
import os
files = os.listdir("/content/ipl_data")
print(len(files))
print(files[:5])

1245
['392235.json', '1136574.json', '1216508.json', '1426267.json', '1529286.json']

In [ ]:
import json
import pandas as pd
with open("/content/ipl_data/1136574.json") as f:
  match =json.load(f)

print(match.keys())
print(match["info"]["teams"])
print(match["info"].get("venue"))
print(match["info"].get("toss"))
print(match["info"].get("outcome"))

dict_keys(['meta', 'info', 'innings'])
['Mumbai Indians', 'Royal Challengers Bangalore']
Wankhede Stadium
{'decision': 'field', 'winner': 'Royal Challengers Bangalore'}
{'winner': 'Mumbai Indians', 'by': {'runs': 46}}

In [ ]:
rows = []
for inn_no, inn in enumerate(match["innings"], start = 1):
  for over in inn["overs"]:
    for ball in over ["deliveries"]:
      rows.append({
          "innings" : inn_no,
          "team" : inn["team"],
          "over" : over["over"],
          "batter" : ball["batter"],
          "bowler" : ball["bowler"],
          "runs_batter" : ball["runs"]["batter"],
          "runs_extra" : ball["runs"]["extras"],
          "runs_total" : ball["runs"]["total"],
          "wickets" : 1 if "wickets" in ball else 0,
      })
      df = pd.DataFrame(rows)
      df.head()

In [ ]:
df.shape

(251, 9)

In [ ]:
df.info()

In [ ]:
df["team"].unique()

array(['Mumbai Indians', 'Royal Challengers Bangalore'], dtype=object)

In [ ]:
df["batter"].nunique()
df[["batter" , "runs_batter"]]

           batter  runs_batter
0        SA Yadav            0
1    Ishan Kishan            0
2       RG Sharma            0
3         E Lewis            1
4       RG Sharma            1
..            ...          ...
246       V Kohli            4
247       V Kohli            0
248       V Kohli            6
249       V Kohli            0
250       V Kohli            0

[251 rows x 2 columns]

In [ ]:
inn1 = df[df["innings"] == 1]
inn1.shape

(127, 9)

In [ ]:
w = df[df["wickets"] == 1]
w[["innings" , "over","batter" , "bowler"]]

     innings  over             batter          bowler
0          1     0           SA Yadav        UT Yadav
1          1     0       Ishan Kishan        UT Yadav
69         1    11            E Lewis     CJ Anderson
95         1    15          RG Sharma     CJ Anderson
113        1    18         KA Pollard       CR Woakes
124        1    19          RG Sharma     CJ Anderson
152        2     4          Q de Kock  MJ McClenaghan
155        2     4     AB de Villiers  MJ McClenaghan
186        2     9      Mandeep Singh       KH Pandya
187        2     9        CJ Anderson       KH Pandya
198        2    11  Washington Sundar       KH Pandya
212        2    13            SN Khan      M Markande
234        2    17          CR Woakes       JJ Bumrah
237        2    17           UT Yadav       JJ Bumrah

In [ ]:
df[(df["innings"] == 2) & (df["runs_batter"] >= 4)]

,innings,team,over,batter,bowler,runs_batter,runs_extra,runs_total,wickets
133,2,Royal Challengers Bangalore,0,V Kohli,JJ Bumrah,4,0,4,0
134,2,Royal Challengers Bangalore,1,Q de Kock,KH Pandya,4,0,4,0
136,2,Royal Challengers Bangalore,1,V Kohli,KH Pandya,4,0,4,0
138,2,Royal Challengers Bangalore,1,V Kohli,KH Pandya,4,0,4,0
145,2,Royal Challengers Bangalore,2,V Kohli,MJ McClenaghan,4,0,4,0
146,2,Royal Challengers Bangalore,3,Q de Kock,Mustafizur Rahman,4,0,4,0
150,2,Royal Challengers Bangalore,3,Q de Kock,Mustafizur Rahman,6,0,6,0
158,2,Royal Challengers Bangalore,5,V Kohli,Mustafizur Rahman,4,0,4,0
160,2,Royal Challengers Bangalore,5,Mandeep Singh,Mustafizur Rahman,4,0,4,0
192,2,Royal Challengers Bangalore,10,Washington Sundar,M Markande,4,0,4,0
207,2,Royal Challengers Bangalore,12,SN Khan,JJ Bumrah,4,0,4,0
208,2,Royal Challengers Bangalore,13,V Kohli,M Markande,6,0,6,0
222,2,Royal Challengers Bangalore,15,V Kohli,Mustafizur Rahman,4,0,4,0
224,2,Royal Challengers Bangalore,15,CR Woakes,Mustafizur Rahman,6,0,6,0
226,2,Royal Challengers Bangalore,16,V Kohli,MJ McClenaghan,6,0,6,0
238,2,Royal Challengers Bangalore,18,V Kohli,Mustafizur Rahman,6,0,6,0
242,2,Royal Challengers Bangalore,18,Mohammed Siraj,Mustafizur Rahman,6,0,6,0
246,2,Royal Challengers Bangalore,19,V Kohli,JJ Bumrah,4,0,4,0
248,2,Royal Challengers Bangalore,19,V Kohli,JJ Bumrah,6,0,6,0

In [ ]:
df.groupby("team")["runs_total"].sum()

team
Mumbai Indians                 213
Royal Challengers Bangalore    167
Name: runs_total, dtype: int64

In [ ]:
top_bat = df.groupby("batter")["runs_batter"].sum()
top_bat = top_bat.sort_values(ascending=False)
top_bat.head(5)

batter
RG Sharma    94
V Kohli      92
E Lewis      65
Q de Kock    19
HH Pandya    17
Name: runs_batter, dtype: int64

In [ ]:
bw = df.groupby("bowler")["wickets"].sum()
bw.sort_values(ascending=False).head(5)

bowler
CJ Anderson       3
KH Pandya         3
MJ McClenaghan    2
JJ Bumrah         2
UT Yadav          2
Name: wickets, dtype: int64

In [ ]:
df.groupby(["innings", "over"]) ["runs_total"].sum()

innings  over
1        0        3
         1       12
         2        6
         3       19
         4       16
         5        4
         6        3
         7       13
         8        9
         9       10
         10      13
         11       6
         12       4
         13      10
         14      15
         15      10
         16      13
         17      11
         18      15
         19      21
2        0        7
         1       13
         2        7
         3       13
         4        4
         5       11
         6        4
         7        6
         8        5
         9        6
         10       8
         11       3
         12       7
         13      10
         14       4
         15      13
         16      13
         17       3
         18      18
         19      12
Name: runs_total, dtype: int64

In [ ]:
runs = df.groupby("batter")["runs_batter"].sum().reset_index()
runs

               batter  runs_batter
0      AB de Villiers            1
1         CJ Anderson            0
2           CR Woakes           11
3             E Lewis           65
4           HH Pandya           17
5        Ishan Kishan            0
6          KA Pollard            5
7           KH Pandya           15
8      MJ McClenaghan            0
9       Mandeep Singh           16
10     Mohammed Siraj            8
11          Q de Kock           19
12          RG Sharma           94
13           SA Yadav            0
14            SN Khan            5
15           UT Yadav            1
16            V Kohli           92
17  Washington Sundar            7

In [ ]:
deliveries = df.groupby("batter").size().reset_index(name="deliveries")
deliveries

               batter  deliveries
0      AB de Villiers           2
1         CJ Anderson           1
2           CR Woakes          11
3             E Lewis          44
4           HH Pandya           5
5        Ishan Kishan           1
6          KA Pollard           8
7           KH Pandya          13
8      MJ McClenaghan           1
9       Mandeep Singh          16
10     Mohammed Siraj           3
11          Q de Kock          13
12          RG Sharma          54
13           SA Yadav           1
14            SN Khan           6
15           UT Yadav           2
16            V Kohli          62
17  Washington Sundar           8

In [ ]:
bat = runs.merge(deliveries, on="batter")
bat["runs_per_delivery"] = bat["runs_batter"] / bat["deliveries"]
bat.sort_values("runs_per_delivery", ascending=False).head(5)

            batter  runs_batter  deliveries  runs_per_delivery
4        HH Pandya           17           5           3.400000
10  Mohammed Siraj            8           3           2.666667
12       RG Sharma           94          54           1.740741
16         V Kohli           92          62           1.483871
3          E Lewis           65          44           1.477273

In [ ]:
x = df.groupby(["innings","over"])["runs_total"].sum().reset_index()
x.sort_values("runs_total" , ascending=False).head(3)

    innings  over  runs_total
19        1    19          21
3         1     3          19
38        2    18          18

In [21]:
import glob, zipfile
for z in glob.glob("/content/*.zip"):
    with zipfile.ZipFile(z) as f:
        names = f.namelist()
        n_json = sum(n.endswith(".json") for n in names)
        print(z, "| total:", len(names), "| json:", n_json)
        if n_json > 100:
            f.extractall("/content/ipl_data")

print(len(glob.glob("/content/ipl_data/**/*.json", recursive=True)))

/content/ipl_json.zip | total: 1245 | json: 1243
1243

In [22]:
import os
print(len(os.listdir("/content/ipl_data")))

1245

In [24]:
import json
with open("/content/ipl_data/1136574.json") as f:
  match = json.load(f)

In [25]:
info = match["info"]
print(info.keys())
print(info.get("toss"))
print(info.get("outcome"))
print(info.get("venue"))
print(info.get("dates"))
print(info.get("season"))

dict_keys(['balls_per_over', 'city', 'dates', 'event', 'gender', 'match_type', 'officials', 'outcome', 'overs', 'player_of_match', 'players', 'registry', 'season', 'team_type', 'teams', 'toss', 'venue'])
{'decision': 'field', 'winner': 'Royal Challengers Bangalore'}
{'winner': 'Mumbai Indians', 'by': {'runs': 46}}
Wankhede Stadium
['2018-04-17']
2018

In [26]:
first = None
for inn in match["innings"]:
  for over in inn["overs"]:
    for ball in over["deliveries"]:
      if "wickets" in ball and first is None:
        first = ball["wickets"]
        print(first)

[{'player_out': 'SA Yadav', 'kind': 'bowled'}]

In [33]:
import os
import json
import pandas as pd

def load_match(path):
    with open(path) as f:
        match = json.load(f)
        info = match["info"]
        toss = info.get("toss", {})
        outcome = info.get("outcome", {})
        dates = info.get("dates", [None])
        base = {
            "match_id": os.path.basename(path).replace(".json", ""),
            "season": info.get("season"),
            "date": dates[0],
            "venue": info.get("venue"),
            "toss_winner": toss.get("winner"),
            "toss_decision": toss.get("decision"),
            "winner": outcome.get("winner"),
            "result": outcome.get("result"),
        }

    rows = []
    for inn_no, inn in enumerate(match.get("innings", []), start=1):
        if inn.get("super_over"):
            continue

        target = inn.get("target", {}).get("runs")
        for over in inn["overs"]:
            for ball in over["deliveries"]:
                wk = ball.get("wickets", [])
                row = dict(base)
                row.update({
                    "innings": inn_no,
                    "team": inn["team"],
                    "target_runs": target,
                    "over": over["over"],
                    "batter": ball["batter"],
                    "bowler": ball["bowler"],
                    "runs_batter": ball["runs"]["batter"],
                    "runs_extra": ball["runs"]["extras"],
                    "runs_total": ball["runs"]["total"],
                    "wickets": len(wk),
                    "player_out": wk[0]["player_out"] if wk else None,
                    "wicket_kind": wk[0]["kind"] if wk else None,
                })
                rows.append(row)

    return pd.DataFrame(rows)

In [34]:
test_df = load_match("/content/ipl_data/1136574.json")
test_df.shape

(251, 20)

In [35]:
folder = "/content/ipl_data"
files = sorted(f for f in os.listdir(folder) if f.endswith(".json"))
print(len(files))

test3 = pd.concat([load_match(os.path.join(folder, f)) for f in files[:3]])
test3.shape

1243

(713, 20)

In [43]:
frames = []
bad = []
for f in files:
  try:        frames.append(load_match(os.path.join(folder, f)))
  except Exception as e:
    bad.append((f, str(e)))
  all_df = pd.concat(frames, ignore_index=True)
  print(all_df.shape)
  print(len(bad))

(248, 20)
0
(495, 20)
0
(713, 20)
0
(960, 20)
0
(1208, 20)
0
(1424, 20)
0
(1678, 20)
0
(1890, 20)
0
(2116, 20)
0
(2355, 20)
0
(2589, 20)
0
(2832, 20)
0
(3068, 20)
0
(3318, 20)
0
(3566, 20)
0
(3817, 20)
0
(4067, 20)
0
(4312, 20)
0
(4561, 20)
0
(4810, 20)
0
(5055, 20)
0
(5280, 20)
0
(5512, 20)
0
(5764, 20)
0
(6009, 20)
0
(6254, 20)
0
(6437, 20)
0
(6682, 20)
0
(6921, 20)
0
(7133, 20)
0
(7354, 20)
0
(7597, 20)
0
(7842, 20)
0
(8092, 20)
0
(8249, 20)
0
(8496, 20)
0
(8741, 20)
0
(8985, 20)
0
(9225, 20)
0
(9463, 20)
0
(9697, 20)
0
(9937, 20)
0
(10183, 20)
0
(10394, 20)
0
(10610, 20)
0
(10854, 20)
0
(11092, 20)
0
(11340, 20)
0
(11583, 20)
0
(11838, 20)
0
(12087, 20)
0
(12315, 20)
0
(12565, 20)
0
(12736, 20)
0
(12985, 20)
0
(13237, 20)
0
(13394, 20)
0
(13601, 20)
0
(13849, 20)
0
(14095, 20)
0
(14333, 20)
0
(14577, 20)
0
(14802, 20)
0
(15048, 20)
0
(15194, 20)
0
(15439, 20)
0
(15676, 20)
0
(15922, 20)
0
(16164, 20)
0
(16415, 20)
0
(16665, 20)
0
(16878, 20)
0
(17129, 20)
0
(17368, 20)
0
(17621, 20)
0
(17866, 20)
0
(18063, 20)
0
(18297, 20)
0
(18543, 20)
0
(18791, 20)
0
(19042, 20)
0
(19272, 20)
0
(19523, 20)
0
(19762, 20)
0
(20008, 20)
0
(20255, 20)
0
(20495, 20)
0
(20741, 20)
0
(20991, 20)
0
(21244, 20)
0
(21428, 20)
0
(21664, 20)
0
(21905, 20)
0
(22138, 20)
0
(22384, 20)
0
(22630, 20)
0
(22866, 20)
0
(23115, 20)
0
(23359, 20)
0
(23593, 20)
0
(23828, 20)
0
(24080, 20)
0
(24331, 20)
0
(24576, 20)
0
(24821, 20)
0
(25060, 20)
0
(25205, 20)
0
(25429, 20)
0
(25680, 20)
0
(25925, 20)
0
(26171, 20)
0
(26412, 20)
0
(26661, 20)
0
(26908, 20)
0
(27155, 20)
0
(27402, 20)
0
(27649, 20)
0
(27894, 20)
0
(28135, 20)
0
(28349, 20)
0
(28593, 20)
0
(28839, 20)
0
(29091, 20)
0
(29337, 20)
0
(29586, 20)
0
(29834, 20)
0
(30077, 20)
0
(30320, 20)
0
(30567, 20)
0
(30811, 20)
0
(31062, 20)
0
(31307, 20)
0
(31553, 20)
0
(31805, 20)
0
(32041, 20)
0
(32287, 20)
0
(32536, 20)
0
(32769, 20)
0
(33013, 20)
0
(33224, 20)
0
(33466, 20)
0
(33697, 20)
0
(33949, 20)
0
(34195, 20)
0
(34434, 20)
0
(34676, 20)
0
(34918, 20)
0
(35163, 20)
0
(35404, 20)
0
(35645, 20)
0
(35893, 20)
0
(36120, 20)
0
(36367, 20)
0
(36620, 20)
0
(36859, 20)
0
(37107, 20)
0
(37325, 20)
0
(37570, 20)
0
(37811, 20)
0
(38055, 20)
0
(38304, 20)
0
(38548, 20)
0
(38783, 20)
0
(39024, 20)
0
(39266, 20)
0
(39512, 20)
0
(39769, 20)
0
(39820, 20)
0
(40043, 20)
0
(40287, 20)
0
(40521, 20)
0
(40745, 20)
0
(40991, 20)
0
(41225, 20)
0
(41453, 20)
0
(41690, 20)
0
(41942, 20)
0
(42181, 20)
0
(42428, 20)
0
(42672, 20)
0
(42922, 20)
0
(43127, 20)
0
(43354, 20)
0
(43606, 20)
0
(43856, 20)
0
(44104, 20)
0
(44348, 20)
0
(44601, 20)
0
(44849, 20)
0
(45063, 20)
0
(45313, 20)
0
(45562, 20)
0
(45802, 20)
0
(46039, 20)
0
(46283, 20)
0
(46537, 20)
0
(46783, 20)
0
(47016, 20)
0
(47253, 20)
0
(47497, 20)
0
(47733, 20)
0
(47971, 20)
0
(48220, 20)
0
(48472, 20)
0
(48717, 20)
0
(48954, 20)
0
(49206, 20)
0
(49443, 20)
0
(49642, 20)
0
(49901, 20)
0
(50145, 20)
0
(50388, 20)
0
(50644, 20)
0
(50870, 20)
0
(51120, 20)
0
(51368, 20)
0
(51615, 20)
0
(51860, 20)
0
(52111, 20)
0
(52358, 20)
0
(52586, 20)
0
(52832, 20)
0
(53041, 20)
0
(53287, 20)
0
(53524, 20)
0
(53776, 20)
0
(54023, 20)
0
(54271, 20)
0
(54513, 20)
0
(54741, 20)
0
(54993, 20)
0
(55233, 20)
0
(55468, 20)
0
(55711, 20)
0
(55959, 20)
0
(56206, 20)
0
(56453, 20)
0
(56703, 20)
0
(56938, 20)
0
(57188, 20)
0
(57427, 20)
0
(57675, 20)
0
(57928, 20)
0
(58173, 20)
0
(58426, 20)
0
(58669, 20)
0
(58889, 20)
0
(59134, 20)
0
(59385, 20)
0
(59622, 20)
0
(59880, 20)
0
(60121, 20)
0
(60357, 20)
0
(60609, 20)
0
(60838, 20)
0
(61070, 20)
0
(61316, 20)
0
(61566, 20)
0
(61814, 20)
0
(62039, 20)
0
(62283, 20)
0
(62523, 20)
0
(62760, 20)
0
(62985, 20)
0
(63231, 20)
0
(63487, 20)
0
(63742, 20)
0
(63973, 20)
0
(64156, 20)
0
(64405, 20)
0
(64641, 20)
0
(64892, 20)
0
(65138, 20)
0
(65375, 20)
0
(65551, 20)
0
(65761, 20)
0
(66007, 20)
0
(66228, 20)
0
(66479, 20)
0
(66728, 20)
0
(66967, 20)
0
(67209, 20)
0
(67460, 20)
0
(67705, 20)
0
(67935, 20)
0
(68184, 20)
0
(68421, 20)
0
(68645, 20)
0
(68891, 20)
0
(69132, 20)
0
(69373, 20)
0
(69623, 20)
0
(69876, 20)
0
(70121, 20)
0
(70356, 20)
0
(70603, 20)
0
(70850, 20)
0
(71098, 20)
0
(71351, 20)
0
(71588, 20)
0
(71827, 20)
0
(72080, 20)
0
(72325, 20)
0
(72580, 20)
0
(72816, 20)
0
(73068, 20)
0
(73278, 20)
0
(73534, 20)
0
(73781, 20)
0
(74026, 20)
0
(74273, 20)
0
(74520, 20)
0
(74738, 20)
0
(74984, 20)
0
(75231, 20)
0
(75466, 20)
0
(75702, 20)
0
(75948, 20)
0
(76198, 20)
0
(76444, 20)
0
(76700, 20)
0
(76952, 20)
0
(77198, 20)
0
(77432, 20)
0
(77681, 20)
0
(77931, 20)
0
(78173, 20)
0
(78419, 20)
0
(78677, 20)
0
(78931, 20)
0
(79121, 20)
0
(79371, 20)
0
(79623, 20)
0
(79876, 20)
0
(80030, 20)
0
(80283, 20)
0
(80542, 20)
0
(80788, 20)
0
(81039, 20)
0
(81280, 20)
0
(81533, 20)
0
(81777, 20)
0
(82024, 20)
0
(82279, 20)
0
(82525, 20)
0
(82776, 20)
0
(83005, 20)
0
(83252, 20)
0
(83505, 20)
0
(83751, 20)
0
(84006, 20)
0
(84217, 20)
0
(84463, 20)
0
(84702, 20)
0
(84935, 20)
0
(85147, 20)
0
(85386, 20)
0
(85584, 20)
0
(85836, 20)
0
(86087, 20)
0
(86331, 20)
0
(86582, 20)
0
(86831, 20)
0
(87086, 20)
0
(87335, 20)
0
(87572, 20)
0
(87819, 20)
0
(88066, 20)
0
(88286, 20)
0
(88538, 20)
0
(88794, 20)
0
(89030, 20)
0
(89263, 20)
0
(89506, 20)
0
(89728, 20)
0
(89979, 20)
0
(90227, 20)
0
(90459, 20)
0
(90719, 20)
0
(90959, 20)
0
(91211, 20)
0
(91447, 20)
0
(91670, 20)
0
(91922, 20)
0
(92161, 20)
0
(92411, 20)
0
(92639, 20)
0
(92892, 20)
0
(93138, 20)
0
(93391, 20)
0
(93639, 20)
0
(93895, 20)
0
(94142, 20)
0
(94391, 20)
0
(94628, 20)
0
(94870, 20)
0
(95122, 20)
0
(95371, 20)
0
(95616, 20)
0
(95852, 20)
0
(96103, 20)
0
(96337, 20)
0
(96578, 20)
0
(96830, 20)
0
(97081, 20)
0
(97333, 20)
0
(97575, 20)
0
(97821, 20)
0
(98068, 20)
0
(98313, 20)
0
(98570, 20)
0
(98803, 20)
0
(99055, 20)
0
(99307, 20)
0
(99565, 20)
0
(99811, 20)
0
(100059, 20)
0
(100177, 20)
0
(100421, 20)
0

/tmp/ipykernel_2001/2597707682.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_df = pd.concat(frames, ignore_index=True)

(100675, 20)
0
(100873, 20)
0
(101104, 20)
0
(101332, 20)
0
(101582, 20)
0
(101832, 20)
0
(102081, 20)
0
(102310, 20)
0
(102565, 20)
0
(102768, 20)
0
(103011, 20)
0
(103255, 20)
0
(103505, 20)
0
(103694, 20)
0
(103937, 20)
0
(104190, 20)
0
(104445, 20)
0
(104694, 20)
0
(104939, 20)
0
(105191, 20)
0
(105447, 20)
0
(105699, 20)
0
(105938, 20)
0
(106186, 20)
0
(106440, 20)
0
(106668, 20)
0
(106910, 20)
0
(107126, 20)
0
(107375, 20)
0
(107621, 20)
0
(107871, 20)
0
(108122, 20)
0
(108369, 20)
0
(108617, 20)
0
(108870, 20)
0
(109126, 20)
0
(109375, 20)
0
(109603, 20)
0
(109850, 20)
0
(110091, 20)
0
(110347, 20)
0
(110570, 20)
0
(110818, 20)
0
(111062, 20)
0
(111309, 20)
0
(111541, 20)
0
(111784, 20)
0
(112035, 20)
0
(112278, 20)
0
(112515, 20)
0
(112766, 20)
0
(113021, 20)
0
(113245, 20)
0
(113484, 20)
0
(113731, 20)
0
(113963, 20)
0
(114212, 20)
0
(114477, 20)
0
(114736, 20)
0
(114903, 20)
0
(115155, 20)
0
(115402, 20)
0
(115647, 20)
0
(115900, 20)
0
(116139, 20)
0
(116384, 20)
0
(116629, 20)
0
(116876, 20)
0
(117130, 20)
0
(117377, 20)
0
(117632, 20)
0
(117876, 20)
0
(118106, 20)
0
(118348, 20)
0
(118575, 20)
0
(118823, 20)
0
(119068, 20)
0
(119328, 20)
0
(119571, 20)
0
(119775, 20)
0
(120024, 20)
0
(120256, 20)
0
(120495, 20)
0
(120747, 20)
0
(120930, 20)
0
(121162, 20)
0
(121411, 20)
0
(121612, 20)
0
(121851, 20)
0
(122098, 20)
0
(122351, 20)
0
(122586, 20)
0
(122845, 20)
0
(123098, 20)
0
(123345, 20)
0
(123553, 20)
0
(123794, 20)
0
(124045, 20)
0
(124229, 20)
0
(124452, 20)
0
(124714, 20)
0
(124957, 20)
0
(125203, 20)
0
(125457, 20)
0
(125691, 20)
0
(125924, 20)
0
(126174, 20)
0
(126431, 20)
0
(126648, 20)
0
(126898, 20)
0
(127080, 20)
0
(127305, 20)
0
(127536, 20)
0
(127764, 20)
0
(128016, 20)
0
(128267, 20)
0
(128520, 20)
0
(128784, 20)
0
(129009, 20)
0
(129262, 20)
0
(129515, 20)
0
(129775, 20)
0
(130011, 20)
0
(130200, 20)
0
(130449, 20)
0
(130697, 20)
0
(130930, 20)
0
(131173, 20)
0
(131427, 20)
0
(131615, 20)
0
(131867, 20)
0
(132109, 20)
0
(132269, 20)
0
(132519, 20)
0
(132765, 20)
0
(133002, 20)
0
(133230, 20)
0
(133479, 20)
0
(133710, 20)
0
(133928, 20)
0
(134181, 20)
0
(134425, 20)
0
(134555, 20)
0
(134806, 20)
0
(135044, 20)
0
(135271, 20)
0
(135528, 20)
0
(135777, 20)
0
(136003, 20)
0
(136253, 20)
0
(136499, 20)
0
(136751, 20)
0
(137004, 20)
0
(137127, 20)
0
(137371, 20)
0
(137615, 20)
0
(137678, 20)
0
(137926, 20)
0
(138167, 20)
0
(138417, 20)
0
(138653, 20)
0
(138885, 20)
0
(139139, 20)
0
(139386, 20)
0
(139628, 20)
0
(139875, 20)
0
(140120, 20)
0
(140364, 20)
0
(140511, 20)
0
(140759, 20)
0
(141003, 20)
0
(141255, 20)
0
(141504, 20)
0
(141729, 20)
0
(141976, 20)
0
(142175, 20)
0
(142425, 20)
0
(142654, 20)
0
(142885, 20)
0
(143136, 20)
0
(143373, 20)
0
(143626, 20)
0
(143868, 20)
0
(144115, 20)
0
(144137, 20)
0
(144281, 20)
0
(144535, 20)
0
(144788, 20)
0
(145021, 20)
0
(145271, 20)
0
(145523, 20)
0
(145760, 20)
0
(146022, 20)
0
(146273, 20)
0
(146528, 20)
0
(146744, 20)
0
(146977, 20)
0
(147226, 20)
0
(147477, 20)
0
(147734, 20)
0
(147990, 20)
0
(148243, 20)
0
(148467, 20)
0
(148722, 20)
0
(148959, 20)
0
(149206, 20)
0
(149445, 20)
0
(149698, 20)
0
(149944, 20)
0
(150172, 20)
0
(150424, 20)
0
(150566, 20)
0
(150808, 20)
0
(151055, 20)
0
(151272, 20)
0
(151521, 20)
0
(151755, 20)
0
(151990, 20)
0
(152238, 20)
0
(152484, 20)
0
(152714, 20)
0
(152968, 20)
0
(153209, 20)
0
(153417, 20)
0
(153651, 20)
0
(153901, 20)
0
(154155, 20)
0
(154407, 20)
0
(154623, 20)
0
(154869, 20)
0
(155118, 20)
0
(155348, 20)
0
(155600, 20)
0
(155854, 20)
0
(156103, 20)
0
(156352, 20)
0
(156603, 20)
0
(156844, 20)
0
(157059, 20)
0
(157317, 20)
0
(157556, 20)
0
(157807, 20)
0
(158052, 20)
0
(158301, 20)
0
(158553, 20)
0
(158794, 20)
0
(159027, 20)
0
(159252, 20)
0
(159500, 20)
0
(159719, 20)
0
(159965, 20)
0
(160205, 20)
0
(160446, 20)
0
(160651, 20)
0
(160906, 20)
0
(161154, 20)
0
(161404, 20)
0
(161633, 20)
0
(161866, 20)
0
(162068, 20)
0
(162316, 20)
0
(162563, 20)
0
(162806, 20)
0
(163049, 20)
0
(163288, 20)
0
(163537, 20)
0
(163781, 20)
0
(164021, 20)
0
(164268, 20)
0
(164506, 20)
0
(164715, 20)
0
(164953, 20)
0
(165189, 20)
0
(165391, 20)
0
(165642, 20)
0
(165839, 20)
0
(166062, 20)
0
(166279, 20)
0
(166532, 20)
0
(166784, 20)
0
(167029, 20)
0
(167250, 20)
0
(167488, 20)
0
(167709, 20)
0
(167954, 20)
0
(168201, 20)
0
(168337, 20)
0
(168460, 20)
0
(168712, 20)
0
(168964, 20)
0
(169139, 20)
0
(169375, 20)
0
(169599, 20)
0
(169848, 20)
0
(170095, 20)
0
(170338, 20)
0
(170585, 20)
0
(170833, 20)
0
(171077, 20)
0
(171325, 20)
0
(171578, 20)
0
(171828, 20)
0
(172051, 20)
0
(172266, 20)
0
(172516, 20)
0
(172760, 20)
0
(172981, 20)
0
(173089, 20)
0
(173288, 20)
0
(173508, 20)
0
(173695, 20)
0
(173942, 20)
0
(174188, 20)
0
(174444, 20)
0
(174686, 20)
0
(174938, 20)
0
(175184, 20)
0
(175437, 20)
0
(175685, 20)
0
(175904, 20)
0
(176144, 20)
0
(176392, 20)
0
(176646, 20)
0
(176889, 20)
0
(177132, 20)
0
(177385, 20)
0
(177632, 20)
0
(177878, 20)
0
(178124, 20)
0
(178373, 20)
0
(178611, 20)
0
(178826, 20)
0
(179078, 20)
0
(179318, 20)
0
(179563, 20)
0
(179781, 20)
0
(180001, 20)
0
(180248, 20)
0
(180495, 20)
0
(180733, 20)
0
(180988, 20)
0
(181222, 20)
0
(181463, 20)
0
(181711, 20)
0
(181945, 20)
0
(182194, 20)
0
(182434, 20)
0
(182685, 20)
0
(182934, 20)
0
(183176, 20)
0
(183424, 20)
0
(183674, 20)
0
(183925, 20)
0
(184175, 20)
0
(184414, 20)
0
(184656, 20)
0
(184901, 20)
0
(185142, 20)
0
(185389, 20)
0
(185626, 20)
0
(185864, 20)
0
(186111, 20)
0
(186365, 20)
0
(186619, 20)
0
(186865, 20)
0
(187108, 20)
0
(187362, 20)
0
(187594, 20)
0
(187842, 20)
0
(188082, 20)
0
(188312, 20)
0
(188507, 20)
0
(188755, 20)
0
(188998, 20)
0
(189242, 20)
0
(189481, 20)
0
(189723, 20)
0
(189973, 20)
0
(190214, 20)
0
(190464, 20)
0
(190710, 20)
0
(190960, 20)
0
(191184, 20)
0
(191439, 20)
0
(191691, 20)
0
(191936, 20)
0
(192175, 20)
0
(192425, 20)
0
(192676, 20)
0
(192917, 20)
0
(193150, 20)
0
(193401, 20)
0
(193643, 20)
0
(193890, 20)
0
(194128, 20)
0
(194367, 20)
0
(194611, 20)
0
(194860, 20)
0
(195117, 20)
0
(195340, 20)
0
(195590, 20)
0
(195841, 20)
0
(196081, 20)
0
(196325, 20)
0
(196557, 20)
0
(196796, 20)
0
(197047, 20)
0
(197296, 20)
0
(197543, 20)
0
(197755, 20)
0
(197972, 20)
0
(198214, 20)
0
(198461, 20)
0
(198709, 20)
0
(198934, 20)
0
(199180, 20)
0
(199424, 20)
0
(199657, 20)
0
(199912, 20)
0
(200153, 20)
0
(200351, 20)
0
(200600, 20)
0
(200844, 20)
0
(201081, 20)
0
(201326, 20)
0
(201544, 20)
0
(201751, 20)
0
(201998, 20)
0
(202236, 20)
0
(202473, 20)
0
(202711, 20)
0
(202957, 20)
0
(203207, 20)
0
(203449, 20)
0
(203696, 20)
0
(203942, 20)
0
(204177, 20)
0
(204424, 20)
0
(204609, 20)
0
(204805, 20)
0
(205049, 20)
0
(205279, 20)
0
(205524, 20)
0
(205773, 20)
0
(206030, 20)
0
(206272, 20)
0
(206521, 20)
0
(206766, 20)
0
(206975, 20)
0
(207221, 20)
0
(207472, 20)
0
(207719, 20)
0
(207947, 20)
0
(208197, 20)
0
(208431, 20)
0
(208677, 20)
0
(208916, 20)
0
(209149, 20)
0
(209390, 20)
0
(209637, 20)
0
(209879, 20)
0
(210105, 20)
0
(210354, 20)
0
(210592, 20)
0
(210840, 20)
0
(211087, 20)
0
(211334, 20)
0
(211580, 20)
0
(211766, 20)
0
(212016, 20)
0
(212227, 20)
0
(212456, 20)
0
(212702, 20)
0
(212936, 20)
0
(213140, 20)
0
(213369, 20)
0
(213615, 20)
0
(213862, 20)
0
(214021, 20)
0
(214270, 20)
0
(214521, 20)
0
(214682, 20)
0
(214925, 20)
0
(215157, 20)
0
(215406, 20)
0
(215633, 20)
0
(215836, 20)
0
(216075, 20)
0
(216138, 20)
0
(216380, 20)
0
(216628, 20)
0
(216877, 20)
0
(217118, 20)
0
(217369, 20)
0
(217613, 20)
0
(217843, 20)
0
(217985, 20)
0
(218232, 20)
0
(218481, 20)
0
(218725, 20)
0
(218958, 20)
0
(219206, 20)
0
(219454, 20)
0
(219697, 20)
0
(219946, 20)
0
(220150, 20)
0
(220391, 20)
0
(220645, 20)
0
(220870, 20)
0
(221116, 20)
0
(221361, 20)
0
(221604, 20)
0
(221847, 20)
0
(222088, 20)
0
(222303, 20)
0
(222552, 20)
0
(222799, 20)
0
(223021, 20)
0
(223246, 20)
0
(223491, 20)
0
(223739, 20)
0
(223983, 20)
0
(224235, 20)
0
(224481, 20)
0
(224723, 20)
0
(224972, 20)
0
(225190, 20)
0
(225439, 20)
0
(225687, 20)
0
(225936, 20)
0
(226184, 20)
0
(226431, 20)
0
(226678, 20)
0
(226910, 20)
0
(227160, 20)
0
(227406, 20)
0
(227622, 20)
0
(227866, 20)
0
(228115, 20)
0
(228360, 20)
0
(228615, 20)
0
(228866, 20)
0
(229114, 20)
0
(229354, 20)
0
(229596, 20)
0
(229817, 20)
0
(230063, 20)
0
(230296, 20)
0
(230539, 20)
0
(230785, 20)
0
(231030, 20)
0
(231248, 20)
0
(231492, 20)
0
(231737, 20)
0
(231993, 20)
0
(232235, 20)
0
(232471, 20)
0
(232716, 20)
0
(232938, 20)
0
(233186, 20)
0
(233429, 20)
0
(233665, 20)
0
(233911, 20)
0
(234158, 20)
0
(234408, 20)
0
(234654, 20)
0
(234903, 20)
0
(235132, 20)
0
(235380, 20)
0
(235619, 20)
0
(235866, 20)
0
(236103, 20)
0
(236351, 20)
0
(236603, 20)
0
(236801, 20)
0
(237049, 20)
0
(237291, 20)
0
(237539, 20)
0
(237766, 20)
0
(238003, 20)
0
(238242, 20)
0
(238485, 20)
0
(238732, 20)
0
(238985, 20)
0
(239232, 20)
0
(239467, 20)
0
(239711, 20)
0
(239959, 20)
0
(240205, 20)
0
(240444, 20)
0
(240685, 20)
0
(240919, 20)
0
(241155, 20)
0
(241392, 20)
0
(241624, 20)
0
(241852, 20)
0
(242096, 20)
0
(242344, 20)
0
(242595, 20)
0
(242839, 20)
0
(243080, 20)
0
(243326, 20)
0
(243559, 20)
0
(243796, 20)
0
(244043, 20)
0
(244292, 20)
0
(244543, 20)
0
(244789, 20)
0
(245040, 20)
0
(245285, 20)
0
(245521, 20)
0
(245754, 20)
0
(245996, 20)
0
(246243, 20)
0
(246477, 20)
0
(246680, 20)
0
(246919, 20)
0
(247139, 20)
0
(247388, 20)
0
(247623, 20)
0
(247860, 20)
0
(248096, 20)
0
(248348, 20)
0
(248588, 20)
0
(248832, 20)
0
(249081, 20)
0
(249318, 20)
0
(249561, 20)
0
(249802, 20)
0
(250029, 20)
0
(250255, 20)
0
(250503, 20)
0
(250747, 20)
0
(250995, 20)
0
(251243, 20)
0
(251481, 20)
0
(251726, 20)
0
(251968, 20)
0
(252218, 20)
0
(252318, 20)
0
(252558, 20)
0
(252792, 20)
0
(253034, 20)
0
(253282, 20)
0
(253532, 20)
0
(253777, 20)
0
(254007, 20)
0
(254253, 20)
0
(254497, 20)
0
(254727, 20)
0
(254976, 20)
0
(255215, 20)
0
(255434, 20)
0
(255679, 20)
0
(255927, 20)
0
(256174, 20)
0
(256419, 20)
0
(256656, 20)
0
(256827, 20)
0
(257064, 20)
0
(257302, 20)
0
(257542, 20)
0
(257782, 20)
0
(258032, 20)
0
(258283, 20)
0
(258489, 20)
0
(258732, 20)
0
(258967, 20)
0
(259217, 20)
0
(259466, 20)
0
(259710, 20)
0
(259962, 20)
0
(260195, 20)
0
(260443, 20)
0
(260689, 20)
0
(260944, 20)
0
(261095, 20)
0
(261341, 20)
0
(261574, 20)
0
(261817, 20)
0
(262056, 20)
0
(262302, 20)
0
(262551, 20)
0
(262793, 20)
0
(263034, 20)
0
(263285, 20)
0
(263530, 20)
0
(263774, 20)
0
(264024, 20)
0
(264277, 20)
0
(264521, 20)
0
(264753, 20)
0
(264996, 20)
0
(265243, 20)
0
(265485, 20)
0
(265728, 20)
0
(265975, 20)
0
(266206, 20)
0
(266420, 20)
0
(266620, 20)
0
(266835, 20)
0
(267080, 20)
0
(267318, 20)
0
(267575, 20)
0
(267820, 20)
0
(268055, 20)
0
(268303, 20)
0
(268558, 20)
0
(268810, 20)
0
(269048, 20)
0
(269300, 20)
0
(269548, 20)
0
(269785, 20)
0
(270025, 20)
0
(270271, 20)
0
(270524, 20)
0
(270773, 20)
0
(271008, 20)
0
(271255, 20)
0
(271486, 20)
0
(271720, 20)
0
(271982, 20)
0
(272220, 20)
0
(272467, 20)
0
(272663, 20)
0
(272907, 20)
0
(273162, 20)
0
(273382, 20)
0
(273634, 20)
0
(273882, 20)
0
(274063, 20)
0
(274308, 20)
0
(274558, 20)
0
(274686, 20)
0
(274936, 20)
0
(275148, 20)
0
(275401, 20)
0
(275528, 20)
0
(275776, 20)
0
(276021, 20)
0
(276276, 20)
0
(276520, 20)
0
(276765, 20)
0
(277009, 20)
0
(277221, 20)
0
(277468, 20)
0
(277707, 20)
0
(277953, 20)
0
(278197, 20)
0
(278445, 20)
0
(278692, 20)
0
(278940, 20)
0
(279160, 20)
0
(279286, 20)
0
(279542, 20)
0
(279648, 20)
0
(279877, 20)
0
(280136, 20)
0
(280266, 20)
0
(280478, 20)
0
(280726, 20)
0
(280968, 20)
0
(281215, 20)
0
(281461, 20)
0
(281679, 20)
0
(281879, 20)
0
(282112, 20)
0
(282362, 20)
0
(282608, 20)
0
(282841, 20)
0
(283048, 20)
0
(283288, 20)
0
(283539, 20)
0
(283776, 20)
0
(284019, 20)
0
(284253, 20)
0
(284484, 20)
0
(284721, 20)
0
(284938, 20)
0
(285192, 20)
0
(285443, 20)
0
(285678, 20)
0
(285924, 20)
0
(286168, 20)
0
(286415, 20)
0
(286611, 20)
0
(286853, 20)
0
(287086, 20)
0
(287338, 20)
0
(287578, 20)
0
(287824, 20)
0
(288069, 20)
0
(288309, 20)
0
(288557, 20)
0
(288786, 20)
0
(289033, 20)
0
(289281, 20)
0
(289523, 20)
0
(289767, 20)
0
(290012, 20)
0
(290238, 20)
0
(290470, 20)
0
(290716, 20)
0
(290960, 20)
0
(291204, 20)
0
(291441, 20)
0
(291669, 20)
0
(291911, 20)
0
(292053, 20)
0
(292296, 20)
0
(292533, 20)
0
(292772, 20)
0
(292965, 20)
0
(293151, 20)
0
(293365, 20)
0
(293612, 20)
0
(293862, 20)
0
(294098, 20)
0
(294345, 20)
0
(294581, 20)
0
(294821, 20)
0
(295065, 20)
0
(295307, 20)
0
(295557, 20)
0

In [45]:
all_df["date"] = pd.to_datetime(all_df["date"])
all_df["year"] = all_df["date"].dt.year
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295557 entries, 0 to 295556
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   match_id       295557 non-null  object
 1   season         295557 non-null  object
 2   date           295557 non-null  datetime64[ns]
 3   venue          295557 non-null  object
 4   toss_winner    295557 non-null  object
 5   toss_decision  295557 non-null  object
 6   winner         290752 non-null  object
 7   result         4805 non-null    object
 8   innings        295557 non-null  int64
 9   team           295557 non-null  object
 10  target_runs    142303 non-null  float64
 11  over           295557 non-null  int64
 12  batter         295557 non-null  object
 13  bowler         295557 non-null  object
 14  runs_batter    295557 non-null  int64
 15  runs_extra     295557 non-null  int64
 16  runs_total     295557 non-null  int64
 17  wickets        295557 non-null  int64
 18  player_out     14674 non-null   object
 19  wicket_kind    14674 non-null   object
 20  year           295557 non-null  int32
dtypes: datetime64[ns](1), float64(1), int32(1), int64(6), object(12)
memory usage: 46.2+ MB

In [46]:
all_df.isna().sum()

match_id              0
season                0
date                  0
venue                 0
toss_winner           0
toss_decision         0
winner             4805
result           290752
innings               0
team                  0
target_runs      153254
over                  0
batter                0
bowler                0
runs_batter           0
runs_extra            0
runs_total            0
wickets               0
player_out       280883
wicket_kind      280883
year                  0
dtype: int64

In [47]:
all_df["match_id"].nunique()

1243

In [48]:
all_df.groupby("match_id")["wickets"].sum().describe()

count    1243.00000
mean       11.80531
std         3.10302
min         1.00000
25%        10.00000
50%        12.00000
75%        14.00000
max        20.00000
Name: wickets, dtype: float64

In [49]:
all_df.groupby("match_id")["wickets"].sum().describe()

count    1243.00000
mean       11.80531
std         3.10302
min         1.00000
25%        10.00000
50%        12.00000
75%        14.00000
max        20.00000
Name: wickets, dtype: float64

In [50]:
all_df.to_csv("/content/ipl_all_balls.csv", index=False)

In [51]:
cols = ["match_id", "date", "year", "season", "venue", "toss_winner","toss_decision", "winner", "result"]
matches = all_df.drop_duplicates("match_id")[cols]
matches.shape

(1243, 9)

In [52]:
matches["year"].value_counts().sort_index()

year
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
2018    60
2019    60
2020    60
2021    60
2022    74
2023    74
2024    71
2025    74
2026    74
Name: count, dtype: int64

In [54]:
y2019 = all_df[all_df["year"] == 2019]
y2019["match_id"].nunique()

60

In [55]:
inn1 = all_df[all_df["innings"] == 1]
per_match = inn1.groupby(["year", "match_id"])["runs_total"].sum().reset_index()
per_match.groupby("year")["runs_total"].mean().round(1)

year
2008    161.0
2009    150.3
2010    164.8
2011    152.4
2012    157.5
2013    155.9
2014    163.1
2015    166.3
2016    162.6
2017    165.8
2018    172.5
2019    166.7
2020    169.5
2021    159.3
2022    171.1
2023    182.7
2024    189.6
2025    188.8
2026    193.0
Name: runs_total, dtype: float64

In [56]:
m = matches.dropna(subset=["winner"]).copy()
m["toss_winner_won"] = (m["toss_winner"] == m["winner"])
print(len(m))
print(m["toss_winner_won"].mean())

1218
0.5155993431855501

In [58]:
m.groupby("toss_decision")["toss_winner_won"].agg(["mean", "count"])

                   mean  count
toss_decision
bat            0.453431    408
field          0.546914    810

In [59]:
m.groupby("year")["toss_winner_won"].agg(["mean", "count"])

          mean  count
year
2008  0.482759     58
2009  0.589286     56
2010  0.525424     59
2011  0.527778     72
2012  0.445946     74
2013  0.472973     74
2014  0.491525     59
2015  0.482143     56
2016  0.566667     60
2017  0.586207     58
2018  0.533333     60
2019  0.596491     57
2020  0.446429     56
2021  0.576271     59
2022  0.486486     74
2023  0.465753     73
2024  0.436620     71
2025  0.614286     70
2026  0.513889     72